### PR TITLE
Initial implementation for downloading existing alerts.

### PR DESCRIPTION
**Pull request by zbazztian**
@johnlugton This just got ready today and it works ok for the scenarios I tested it with, but I wouldn't use it in production yet. If you can wait until tomorrow I might have it refactored a bit better and potentially with synchronization from the JIRA side.

### CODE REVIEW

**Comment by zbazztian** [comment]
It takes 3 new parameters:
* `GH_API_URL`: **Api** url for the GitHub instance (e.g. `https://api.github.com` or `https://your-instance/api/v3/`) (we could derive it from a given plain GitHub url, but they are different for GH Server and GH Cloud, so I opted to make it explicit for now.
* `GH_USERNAME`
* `GH_TOKEN`: Api token with the appropriate permissions to download (and later change / update) alerts.

**Comment by zbazztian** [comment]
@johnlugton I added a second commit with the functionality I demoed today. I only worked two days on this, so there surely are a few things which require thorough testing, but the basics work. Will get to this next year. Ideally, we can get together some day and discuss some of the details.

**Comment by johnlugton** [comment]
Thanks for all your help with this - looking really good. I spoke to quickbase yesterday and main requests were:
 - they want to do more complex mapping from repo & code path to jira project (which is a pain because we don't have path in the webhook event)
 - they are fine with a script that runs nightly

Let's meet in jan to figure it out, but I was thinking of refactoring to:
 - library with most of the logic for talking to jira and GH
 - flask webserver wrapper that consumes webhooks from both (and maybe tries sync on startup?)
 - cli wrapper that can be used if you want to run on actions and do a nightly sync, or e.g. wire up webhooks with AWS lambdas

**Comment by zbazztian** [comment]
> they want to do more complex mapping from repo & code path to jira project (which is a pain because we don't have path in the webhook event)

Yeah, as far as I can tell that information is not even available via any API call at the moment. Unless one somehow downloads the SARIF file there doesn't seem to be a way to get to it. The only thing that comes to mind right now is scraping it from the web page that the alert's html link points to ...

> Let's meet in jan to figure it out, but I was thinking of refactoring to:
>   * library with most of the logic for talking to jira and GH
>   * flask webserver wrapper that consumes webhooks from both (and maybe tries sync on startup?)
>   * cli wrapper that can be used if you want to run on actions and do a nightly sync, or e.g. wire up webhooks with AWS lambdas

Sounds all good to me. Having all of this in a library will make customizations much easier. January, it is. Until then: Happy Holidays!

**Comment by zbazztian** [comment]
@johnlugton Just so we don't step on each other's toes, I plan to do some refactoring into a library, as discussed, unless you are already doing this. I'll keep it functional the way it is right now, but will make it easier to reuse things for a future CLI tool.
There are also a couple of other things that I'd like to address, such as downloading secret scanning results, and potentially Dependabot alerts (not sure yet whether there is an appropriate API for this available).

Either way, I'll split this up into a series of smaller PRs in the coming days.

Also, I was approached by @iamwillbar and @mayakacz about integrating this with the new Security Center. They are working on a consolidated API that we could use to download all those different types of alerts. It might also be a chance for us to express our interest in specific fields (Alert locations, etc.) if they don't exist in this API yet. They specifically asked us what endpoints / fields we need, so they might be open to suggestions. I said I would get back to them in 2 weeks time, when this whole thing is a bit more mature.

**Comment by johnlugton** [comment]
I sent a small PR to reduce duplication and will probably update to split into CLI later today. After that I should have enough to keep customer happy so will probably leave the rest to you.

**Pull request merged**
