### PR TITLE
WIP: Split code into cli and server versions

### PR DESCRIPTION
**Pull request by johnlugton**
@zbazztian this splits existing code into a library (common.py) and flask wrapper (server.py). I've also added a CLI tool to perform full sync for customers that just want to run on actions/cron.

I haven't actually tested any of this yet, so still WIP.

### CODE REVIEW

**Comment by zbazztian** [comment]
@johnlugton Apologies for the poor communication on my part. I have already started working on a cli tool and made a few more changes to improve stability. I also split up the code scanning and jira functions into separate modules. Since it seems that this PR draft is so far only moving things around and introduced a cli skeleton, would you mind if I put mine up today for you to have a look?

**Comment by johnlugton** [comment]
No problem! Yes if you have a tested/working version I would be very happy to use that

**Comment by zbazztian** [comment]
Cheers! I'll tidy up some things up and will put up my code.

**Comment by zbazztian** [comment]
Still working on this, will update soon.

**Pull request closed without merging**
