### PR TITLE
Two-way integration for the "sync" command

### PR DESCRIPTION
**Pull request by zbazztian**
This implements two-way integration for the `sync` command by teaching it to store all alert (and issue) states in a json file. By two-way integration I am referring to the following behavior:
* Dismissing an alert will close its ticket
* Opening a ticket will re-open its alert.
* This is opposed to one-way integration, where either the alert states or the issue states are taken as source of truth.

To use this feature, one will have to supply `--direction both` and `--states-file /path/to/states.json`.

In a follow-up PR, I plan to teach the GitHub Action to use this feature. I am still trying to find a good place for storing the state file. Current candidates are:
* Within the same repository. The problem with this approach is that, depending on how often the action is running, it might inflate the repository's commit count. In addition it could accidentally trigger workflows or webhooks. However, it might be acceptable if the file is on a dedicated branch.
* Within a separate repository.
* In a dedicated GitHub issue or wiki page, ... A bit hacky, but it wouldn't suffer from the above problems.
* In JIRA, within each alert issue. Unfortunately, this would require updating each ticket during each synchronization, which is costly and could set off JIRA triggers / webhooks.
* In JIRA, in a dedicated state issue (hacky).

@cmboling @johnlugton

### CODE REVIEW

**Comment by zbazztian** [comment]
I am lobbying for [additional fields in the API](https://github.com/github/code-scanning/issues/2983), which would make this PR and possible follow-ups unnecessary. So, perhaps we can hold off for now and see what happens.

**Comment by zbazztian** [comment]
Lobbying isn't going very well, so I think I'll flesh this PR out a bit more and see whether I can store the state in one of the locations described above. I do think that this will make the action much more usable to many customers. Should we have additional fields in the API responses at some point, we can always make use of those, but my feeling is that this will not happen in the near future.

**Comment by zbazztian** [comment]
I added a few more commits which allow the `sync` command and the action to store a repository's state in a JIRA ticket. That means, both, the `sync` command and the action, can now perform two-way synchronization. The following command will create a dedicated JIRA issue and attach the state of the `newrepository` repository as a JSON file:
```bash
export GH2JIRA_GH_TOKEN=...
export GH2JIRA_JIRA_TOKEN=...
./gh2jira sync \
              --gh-url https://api.github.com \
              --gh-org ghas-performance-testing \
              --gh-repo jira-integration \
              --jira-url https://jira.demo-stack.com \
              --jira-user zbazztian \
              --jira-project JIR \
              --direction both \
              --state-issue -
```
Instead of `-` it is possible to specify the key of a specific issue (possibly in a different project). Then the state will be stored there.

Here an example using the new `--state-file` option:
```bash
export GH2JIRA_GH_TOKEN=...
export GH2JIRA_JIRA_TOKEN=...
./gh2jira sync \
              --gh-url https://api.github.com \
              --gh-org ghas-performance-testing \
              --gh-repo jira-integration \
              --jira-url https://jira.demo-stack.com \
              --jira-user zbazztian \
              --jira-project JIR \
              --direction both \
              --state-file jira-integration.json
```

Here is what a state file for a repository looks like:
```json
{
  "1": true,
  "2": true,
  "3": true,
  "4": true,
  "5": true,
  "6": true,
  "7": true,
  "8": true,
  "9": true,
  "10": true,
  "11": true,
  "12": true,
  "13": true,
  "14": true,
  "15": true,
  "16": true,
  "17": true,
  "18": true,
  "19": true,
  "20": true,
  "21": true,
  "22": true,
  "23": true,
  "24": true,
  "25": true,
  "26": true,
  "27": true,
  "28": true,
  "29": true,
  "30": true,
  "31": true,
  "32": true,
  "33": true,
  "34": true,
  "35": true,
  "36": true,
  "37": true,
  "38": true,
  "39": true,
  "40": true,
  "41": true,
  "42": true,
  "43": true,
  "44": true,
  "45": true,
  "46": true,
  "47": true,
  "48": true,
  "49": true,
  "50": true,
  "51": true,
  "52": true,
  "53": true,
  "54": true,
  "55": true,
  "56": true,
  "57": true,
  "58": true,
  "59": true,
  "60": true,
  "61": true,
  "62": true,
  "63": true,
  "64": true,
  "65": true,
  "66": true,
  "67": true,
  "68": true,
  "69": true,
  "70": true,
  "71": true,
  "72": true,
  "73": true,
  "74": true,
  "75": true,
  "76": true,
  "77": true,
  "78": true,
  "79": true,
  "80": true,
  "81": true,
  "82": true,
  "83": true,
  "84": true,
  "85": true,
  "86": true,
  "87": true,
  "88": true,
  "89": true,
  "90": true,
  "91": true,
  "92": true,
  "93": true,
  "94": true,
  "95": true,
  "96": true,
  "97": true,
  "98": false,
  "99": true,
  "100": true,
  "101": true,
  "102": false,
  "103": true
}
```

The rest of the commits
* make the action use this functionality
* split out the synchronization functionality into its own module, to avoid cyclic imports
* update the documentation
* refactor a few things

@cmboling Let me know what you think about this. I think we need to store the state of the repository somewhere to make the action and the `sync` command useful.

/cc @johnlugton

**Comment by cmboling** [comment]
Hey @zbazztian, looks good so far. I'll test this out some time this week. For the action, are there an event triggers that you don't recommend using where the bi-directional sync isn't necessary, like a workflow_dispatch?

**Comment by zbazztian** [comment]
I think this action only makes sense with the `workflow_dispatch` (if one wants to kick off the action manually, e.g. for demo purposes) and `schedule` event triggers. I can't really imagine any other triggers people might want to use this with. John and I were [lobbying for code scanning related triggers](https://github.com/github/code-scanning/issues/2624), but they decided that they don't want those.

I feel bi-directional (i.e. `both`) mode is probably what most people want. Uni-directional, e.g. `gh2jira` will just sync any changes on the GitHub side to JIRA. So if an alert is fixed, it closes the JIRA ticket. But if someone opens a JIRA ticket, it will not open the alert (it will close the ticket again if the corresponding alert is closed). If customers just want to mirror the alerts into JIRA this might be enough for them.

**Comment by zbazztian** [comment]
Hmm, I suppose the [workflow_run](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_run) event might be interesting for this as well. If I understand it right, we could trigger the sync after a successful run of a Code Scanning analysis. I'll have to experiment with that first though.

**Comment by cmboling** [comment]
Yeah it could also be a separate job like so
```
jira-sync:
    name: Jira sync
    runs-on: ubuntu-latest
    needs:
      - analyze 
    steps:
      - name: This gh jira action
      ...
      ...
      ...
```
https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idneeds

**Comment by zbazztian** [comment]
Ah, indeed!

**Comment by zbazztian** [comment]
@cmboling I am going to merge this unless you have any concerns. I plan to move the repository to https://github.com/github/codescanning-jira-integration , which I think is a better name. In addition we can then create issues. It will be private for now, but we can give selected customers access until we have properly open-sourced it.

**Comment by cmboling** [comment]
@zbazztian This is good to merge, thanks so much 🙌🏼

**Pull request merged**
